# Generated by Django 5.0.1 on 2024-01-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roll',
            old_name='winings',
            new_name='winings_multyplier',
        ),
        migrations.AddField(
            model_name='roll',
            name='winning_lines',
            field=models.JSONField(default='{}'),
        ),
        migrations.AlterField(
            model_name='roll',
            name='roll_board',
            field=models.JSONField(),
        ),
    ]
