# Generated by Django 5.0.1 on 2024-01-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0004_alter_roll_winning_lines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roll',
            name='roll_board',
        ),
        migrations.RemoveField(
            model_name='roll',
            name='winning_lines',
        ),
        migrations.AddField(
            model_name='roll',
            name='board_info',
            field=models.JSONField(default=''),
        ),
    ]
