# Generated by Django 5.0.1 on 2024-01-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0005_remove_roll_roll_board_remove_roll_winning_lines_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roll',
            name='board_info',
            field=models.JSONField(default='dict'),
        ),
    ]
