# Generated by Django 5.0.1 on 2024-02-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0009_alter_roll_cost_alter_roll_winings_multyplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roll',
            name='scatter_multiplier',
            field=models.FloatField(default=0),
        ),
    ]
