# Generated by Django 5.0.1 on 2024-02-15 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0010_roll_scatter_multiplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roll',
            old_name='winings_multyplier',
            new_name='winings_multiplier',
        ),
    ]
